# Generated by Django 5.0 on 2024-01-21 19:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0003_avatarimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvatarImage',
            new_name='Avatar',
        ),
    ]
